### ISSUE TITLE
ServiceProvider: settings merge

### ISSUE THREAD

**Issue by candrianarijaona** [kitchenu/Slim-DebugBar#2]
```
foreach ($settings as $key => $setting) {
            $this->settings[$key] = array_merge($this->settings[$key], $setting);
        }
```
If $this->settings[$key] is not an array? 

Use `array_replace_recursive` instead: 

`$this->settings = array_replace_recursive($settings, $this->settings)`

**Comment by kitchenu** [comment]
Thank you for letting me know.
I didn't know the function.
